version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: badminton_postgres
    environment:
      POSTGRES_USER: badminton
      POSTGRES_PASSWORD: badminton
      POSTGRES_DB: badminton
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "badminton"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
    driver: local


